### ISSUE TITLE
Define and implement meaningful non-technical metrics

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando-incubator/api-discovery#102]
**As** a service operator
**I want** to have some information about the operational state of the API discovery tooling
**So that** I'm able to analyze the usage of the tooling and improve it.

**Possible metrics**
- Number of active APIs
- Number of active Applications
- Number of users
- New/old APIs ratio
- New APIs per day
- ..

**Comment by maschleg** [comment]
@maxim-tschumak I guess this is already done?

**Comment by maxim-tschumak** [comment]
yes :)
