### ISSUE TITLE
Extend crawling statuses

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando-incubator/api-discovery#109]
**As** API Management Team
**We want** to have multiple unsuccessful statuses of the crawling in the API storage service
**So that** we have more detailed information about the failed crawlings

**Acceptance criteria**
- Specific Error Handling in the Crawler
- More specific UNSUCCESSFUL statuses in the Crawler
- More specific UNSUCCESSFUL statuses in the Storage
- Lifecycle manager is adjusted to the new statutes (maybe a state machine?)

**Comment by maschleg** [comment]
@maxim-tschumak does this issue still makes sense for the new API end point?

**Comment by maxim-tschumak** [comment]
I think we can remove this issue - at least for now, as we don't have any concrete requirements or need from the customer perspective.
