### ISSUE TITLE
Consolidate DB migration scripts

### ISSUE THREAD

**Issue by tkrop** [zalando-incubator/api-discovery#115]
**As a** developer
**I want** to have only the lowest number of possible db migration scripts
**So that** the final state of the database can be guessed by looking on the scripts

As we have not rolled out the latest features in continuous deployment, it may be a good idea to consolidate the DB migration scripts `V8`,`V9`,`V10` into script `V8` to have a clear view on the actual resulting DB.

As far as I can say we seem to have an unnecessary field `id` in `api_versions`.

**Comment by fmueller** [comment]
The storage was rolled out in between for a bugfix.
