### ISSUE TITLE
POST /api-definitions causes JpaSystemException 

### ISSUE THREAD

**Issue by maschleg** [zalando-incubator/api-discovery#129]
**Current Behavior:** 
When calling POST /api-definitions :
```
org.springframework.orm.jpa.JpaSystemException: ids for this class must be manually assigned beforeQuery calling save(): org.zalando.apidiscovery.storage.repository.ApplicationEntity; nested exception is org.hibernate.id.IdentifierGenerationException: ids for this class must be manually assigned beforeQuery calling save()
```
is thrown.

**How to reproduce:**
Hard to say. Logging has to be improved. It appears whenever the crawler is calling 
POST /api-definitions

**Expected Behavior:**
Api definition should be persisted.

**Comment by fmueller** [comment]
The error message is clear: we try to save an `ApplicationEntity` object with a not set `name`field, which is the primary key.

**Comment by fmueller** [comment]
After having a look into the code: in `newApplication` in `ApiDefinitionProcessingService`we read the name from the supplied api definition. If this value which was posted by the crawler is `null` we persist a non-existent primary key --> exception. That's the issue.

**Comment by fmueller** [comment]
Further analysis: the new crawler code is buggy. For unsuccessful api definitions he pushed `null` values for api name and app name, see `ApiDiscoveryStorageGateway.pushApiDefinition`. It's a bug in the crawler and the storage should check if all necessary fields are in the request before starting processing logic.

**Comment by maxim-tschumak** [comment]
I agree with @fmueller and propose not to push failed crawlings since we don't really need this information in api-repository. We can discuss this after the stand-up.

**Comment by maschleg** [comment]
@fmueller thanks for the analysis
