### ISSUE TITLE
Wrong implementation of CrawledAPIDefinitionResource field app_name 

### ISSUE THREAD

**Issue by maschleg** [zalando-incubator/api-discovery#134]
Specification and implementation differ for CrawledAPIDefinitionResource:
DTO field in class DiscoveredApiDefinition "applicationName" must be renamed to "appName" .

**Comment by fmueller** [comment]
Is this the reason for the `BadRequest` exceptions in the logs?

**Comment by maschleg** [comment]
yes because the field is required but is always null
