### ISSUE TITLE
Crawler gateways Json serialization is Camel_Case

### ISSUE THREAD

**Issue by maschleg** [zalando-incubator/api-discovery#137]
**Current behavior**
Crawler gateways Json serialization is configured has default configuration: CAMEL_CASE

**Expected behavior**
serialization must be SNAKE_CASE

**Analysis**
Defined ObjectMapper in ``JacksonConfiguration.class`` is not the same as in the RestTemplate. Custom ObjectMapper has to be configured: https://stackoverflow.com/questions/9381665/how-can-we-configure-the-internal-jackson-mapper-when-using-resttemplate

**Comment by fmueller** [comment]
Solution should not be too tricky: we already construct our custom `RestTemplate` in `ClientConfiguration`. We need to add correct `ObjectMapper` if I understood it correct.

Good finding @maschleg :)
