### ISSUE TITLE
Database field api_version.api_name must not blank

### ISSUE THREAD

**Issue by maschleg** [zalando-incubator/api-discovery#140]
**Current behavior** 
It is possible to persist an api_version with an blank api_name. As api_name is part of the unique constraint this must be prevent.  

**How to repoduce**
Post /api-defintions with an empty title in the definition. 

**Expected behavior** 

Solution must be clarified: 
1. Post /api-defintions returns a Bad Request
2. We have mechanism to persist invalid api definitions

**Comment by maxim-tschumak** [comment]
I would prefer to have a validation of the request in place and return `BadRequest` in the case of empty API name.

**Comment by fmueller** [comment]
I also vote for `BadRequest` in this case.
