### ISSUE TITLE
API Discovery User Interface

### ISSUE THREAD

**Issue by mfellner** [zalando-incubator/api-discovery#155]
### What
Design and implement a user interface for Swagger UI that makes it easy to discover a particular API definition.

### Why
The current implementation of a drop-down list of available APIs has several drawbacks:

* not enough information to find an API (names are derived from IDs)
* is not searchable
* generally bad UX when the list is long
* does not scale to higher numbers of APIs

### Requirements
A new user interface for API discovery should serve the following needs:

* users can find an API by the title of the Open API definition
* users are not overwhelmed by the number of available API definitions
* the interface can support future UI refinements, e.g. filtering by certain attributes, displaying multiple versions of an API definition, etc.

### Proposal
**API fuzzy search interface.** A large search box allows users to enter text (e.g. the title of the API definition) in order to filter a list of at most `N` results sorted by criterion `C` that match the entered text.

* ✅  can be naively implemented as full-text search on API definitions
* ✅  as the user enters more text, the number of search results quickly drops
* ✅  users who know what they are looking for are getting results fast
* ⚠️  full-text search may be slow
* ⚠️  full-text search may yield ambiguous results
* ⚠️  no overview of total collection of API definitions

**Comment by maxim-tschumak** [comment]
> can be naively implemented as full-text search on API definitions

I think the API `info.title` and `info.description` would be a good start. Optionally, we can add resource definition names.
> full-text search may yield ambiguous results

An easy solution would be to set a minimal length of the search query.
