### ISSUE TITLE
/apis/{id}/versions/{version} always returns 404

### ISSUE THREAD

**Issue by mfellner** [zalando-incubator/api-discovery#156]
### What
The ...versions/{version} endpoint always returns 404.

### Expected
* If an api with versions exists: /apis/{id}/versions.
* Each version /apis/{id}/versions/{version} should also exist.

**Comment by maschleg** [comment]
Spring truncates dots of path variables at the end of the request mapping. So it currently doesn't work for all versions with a dot.  A regex should fix it.
