### ISSUE TITLE
Include createdAt field in ApiDefinition

### ISSUE THREAD

**Issue by mfellner** [zalando-incubator/api-discovery#157]
**As** an API consumer
**I want** to distinguish ApiDefinitions from each other
**and** select the latest (last created) ApiDefintion for a given ApiVersion
**So that** I can directly select an ApiDefinition for a given ApiVersion without making assumptions

### Proposal

org.zalando.apidiscovery.storage.domain.model.ApiDefinition should include a createdAt field.

An API version (org.zalando.apidiscovery.storage.domain.model.Versions) can contain multiple API Definitions. With this solution we can order them by creation date and a client can easily pick the latest one.

### Other ideas

* Server-side filtering, e.g. with `latest` query parameter
* Expose incremental ApiDefinition ID. The highest ID value is equivalent to the latest ApiDefinition.
* Rely on ApiDefinition list ordering convention. Last list entry is equal to the latest ApiDefinition.

**Comment by maschleg** [comment]
Can you please rephrase the issue as user story? I guess the Why is that you actual want to display the latest version first!?

**Comment by maschleg** [comment]
Thanks for rephrase this issue. However, we should rephrase the content again as our PO want's to display the latest version, which is deployed on production, as default.
