### ISSUE TITLE
Fulltext Search Support

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/api-discovery#19]
We wanna add fulltext search support to API Discovery.

In this issue we gather requirements and ideas for this.

**Comment by maxim-tschumak** [comment]
I think we can make use of Posrtgres' full-text indices for the start. Or, we could implement sophisticated search mechanism by introducing Elasticsearch, which is probably much better in long term.

**Comment by fmueller** [comment]
I once implemented a thin wrapper on top of Elasticsearch with automatic diff calculation (for versioning quite nice I guess): https://github.com/pivio/pivio-server You can push any json document into Pivio and it will offer you full-text search on it + changelog calculation.

We could reuse this and enhance it for our needs.
