### ISSUE TITLE
Improve Frontend Development Workflow

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/api-discovery#24]
At the moment it's quite hard to implement a feature in the swagger-ui frontend or fix a bug their:
- no test data
- OAuth server necessary

Some test data should be provided and it should be easy to disable OAuth for development purpose.

**Comment by maxim-tschumak** [comment]
IMO, it would be easier to add test data using storage API when we have a one-command script (#8) to start the whole application stack. It will also enable us to do proper integration testing locally.

**Comment by fmueller** [comment]
Agreed. I created #31 and close this one.
