### ISSUE TITLE
Allow multiple api definitions per service

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/api-discovery#3]
The current schema-discovery endpoint (".well-known/schema-discovery") only supports one api definition. We know that there are services offering more than one api. This has to be supported as well.

**Comment by jpalomaki** [comment]
IMO, assuming path-based routing behind edge LB and one domain, to different micro-sized services, a nice abstraction would be to have services return e.g. this sort of structure (JSON to programmatic consumers, and **maybe optionally** HTML with links to humans for immediate discoverability) by just hitting root `/`:
```
GET /
Host: service.zalan.do
Accept: application/json
=>
200 OK
Content-Type: application/json
{
    "apis" : [
        "/first/swagger.yaml",
        "/second/swagger.yaml",
        ...
    ]
}
```
Then
```
GET /first/swagger.yaml
GET /second/swagger.yaml
...
```
Maybe this sort of thing could complement the current `.well-known/schema-discovery` thingie.
