### ISSUE TITLE
JS in the front page sometimes throws an uncaught Error (90+ %)

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando-incubator/api-discovery#50]
**Error**: `Uncaught TypeError: Cannot read property 'length' of undefined` (index.js:24)
**Impact** No impact so far, but still ugly, we should fix it
**How to reproduce**: Go to the home page and refresh it one or two times.

**Comment by fmueller** [comment]
After some investigation: this seems to be Swagger UI related and depends on given Swagger spec. There is also some issue open (see https://github.com/swagger-api/swagger-ui/issues/1755).

**Comment by fmueller** [comment]
@maxim-tschumak Because of reason above, I'd close this for now and monitor with 'real' data later. What do you think?

**Comment by maxim-tschumak** [comment]
I agree with you, thanks for investigation!
