### ISSUE TITLE
Fix api definition of new API based on Zally feedback

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/api-discovery#72]
Zally found some Must violations which we should fix.

**Comment by fmueller** [comment]
Futhermore, remove client side generated ID in PUT api-definition endpoint.

**Comment by fmueller** [comment]
Add: app_name to payload of PUT api-definition endpoint.

**Comment by fmueller** [comment]
Consider @tkrop feedback: https://github.com/zalando-incubator/api-discovery/pull/44#pullrequestreview-27337233

**Comment by tkrop** [comment]
@fmueller You see me puzzled... isn't api a top-level resource?

**Comment by fmueller** [comment]
@tkrop Regarding your suggestions to move applications to top-level resource.
