### ISSUE TITLE
Rename projects to api infrastructure product

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/api-discovery#74]
As propose by @tfrauenstein we should rename our projects:

- crawler --> api-discovery
- storage --> api-repository
- swagger-ui --> api-portal

The repository itself should be renamed to api-infrastructure.

After this was finished the Github issue labels should be renamed as well, according to corresponding sub-project name.

**Comment by maschleg** [comment]
I changed the names in yourturn
